-   id: black
    name: black
    description: ''
    entry: black
    language: python
    'types': [python,pyi]
    args: []
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: '0'
